"""Natural-language command aliases — normalize before routing."""

from __future__ import annotations

import re

# Short phrases users type/say → canonical utterances the brain already understands
# Keep aligned with jarvis/ui/widgets/control_strip.py button cmds + tip labels.
_ALIASES: list[tuple[str, str]] = [
    (r"^(hi|hello|hey)( jarvis)?$", "how are you"),
    (r"^status$", "status"),
    (r"^(hub|agents?) status$", "hub status"),
    (r"^start( the)? hub$", "start hub"),
    (r"^(stop|halt)( the)? (hub|agents?)$", "hub standby"),
    (r"^standby$", "hub standby"),
    (r"^hub standby$", "hub standby"),
    # Hub agents (button labels + ask-X)
    (r"^sarah$", "sarah triage support tickets"),
    (r"^ask sarah$", "sarah triage support tickets"),
    (r"^tom$", "investigate the checkout bug and open a PR"),
    (r"^ask tom$", "investigate the checkout bug and open a PR"),
    (r"^admin$", "schedule a meeting with the client who complained in support"),
    (r"^ask admin$", "schedule a meeting with the client who complained in support"),
    (r"^(see|read )?screen$", "look at my screen"),
    (r"^help me$", "help"),
    (r"^help$", "help"),
    (r"^build$", "build a site"),
    (r"^site$", "build a site"),
    (r"^vibe$", "start vibe coding"),
    (r"^map$", "open map view"),
    (r"^show map$", "open map view"),
    (r"^open map$", "open map view"),
    (r"^tactical map$", "open map view"),
    (r"^zoom in$", "zoom in"),
    (r"^zoom out$", "zoom out"),
    (r"^zoom closer$", "zoom in"),
    (r"^pull back$", "zoom out"),
    (r"^news$", "pull up the news"),
    (r"^dispatch$", "put on local dispatch"),
    (r"^scanner$", "put on local dispatch"),
    (r"^police radio$", "play police radio"),
    (r"^stop scanner$", "stop scanner"),
    (r"^edit site$", "change the layout of my website"),
    (r"^customize site$", "change the layout of my website"),
    (r"^cam(era|rea)?$", "open camera"),
    (r"^camrea$", "open camera"),
    (r"^webcam$", "open camera"),
    (r"^emeet$", "open camera"),
    (r"^music$", "play music"),
    (r"^playlist$", "play my focus playlist"),
    (r"^mail$", "check email"),
    (r"^ops$", "show ops"),
    (r"^stats$", "show stats"),
    (r"^show stats$", "show stats"),
    (r"^away$", "away mode"),
    (r"^biz$", "find biz"),
    (r"^find biz$", "find biz"),
    (r"^search$", "search the web for latest AI news"),
    # DESK strip labels (spoken short forms)
    (r"^enroll$", "enroll my face"),
    (r"^security$", "security status"),
    (r"^(nv|n\.?v\.?|night vision) on$", "night vision on"),
    (r"^(nv|n\.?v\.?|nvg) off$", "night vision off"),
    (r"^nvg on$", "night vision on"),
    (r"^lock off$", "auto lock off"),
    (r"^audit$", "self audit"),
    (r"^router$", "router status"),
    # "secure" alone = Secure button → desk lock (not secure workflow)
    (r"^secure$", "secure desk"),
    (r"^secure desk$", "secure desk"),
    (r"^secure workflow$", "run secure workflow"),
    (r"^panic$", "panic"),
    # Lights / lamp
    (r"^lamp$", "turn on the lamp"),
    (r"^lights? on$", "turn on the lamp"),
    (r"^lights? off$", "turn off the lamp"),
    (r"^lamp on$", "turn on the lamp"),
    (r"^lamp off$", "turn off the lamp"),
    # Desktop quickies
    (r"^lock$", "lock"),
    (r"^unlock$", "unlock my pc"),
    (r"^unlock (pc|computer)$", "unlock my pc"),
    (r"^ops$", "show ops"),
    (r"^pdtester$", "open pdtester"),
    (r"^digests?$", "open pdtester"),
    (r"^devlog$", "open pdtester"),
    (r"^screenshot$", "take a screenshot"),
    (r"^shot$", "take a screenshot"),
    (r"^mute$", "mute"),
    (r"^unmute$", "unmute"),
    (r"^vol(ume)? up$", "volume up"),
    (r"^vol(ume)? down$", "volume down"),
    (r"^weather$", "weather"),
    (r"^time$", "what time is it"),
    (r"^date$", "what time is it"),
    (r"^time in cali$", "what time is it in cali"),
    (r"^time in california$", "what time is it in california"),
    (r"^what time in cali$", "what time is it in cali"),
    (r"^what time('?s| is it)? in cali$", "what time is it in cali"),
    (r"^brief(ing)?$", "good morning"),
    (r"^standup$", "good morning"),
    (r"^mic( test)?$", "test microphone"),
    (r"^reload$", "reload core"),
    (r"^cast to tv$", "cast to tv"),
    (r"^cast to fire tv$", "cast to tv"),
    (r"^project to tv$", "cast to tv"),
    (r"^jarvis on tv$", "cast to tv"),
    (r"^mirror to tv$", "cast to tv"),
    (r"^jarvis optimize$", "optimize jarvis"),
    (r"^lean mode$", "optimize jarvis"),
    (r"^upgrade everything$", "upgrade everything"),
    (r"^fix everything$", "upgrade everything"),
    (r"^make (it |everything )?better$", "upgrade everything"),
    (r"^upgrade (jarvis|ar)$", "upgrade everything"),
    (r"^optimize ar$", "upgrade everything"),
    (r"^list reminders$", "list reminders"),
    (r"^my reminders$", "list reminders"),
    (r"^cancel reminders$", "cancel all reminders"),
    (r"^smooth mode$", "smooth mode"),
    (r"^offline$", "go offline"),
    (r"^work$", "start work"),
    (r"^sleep$", "sleep"),
    (r"^phone$", "link my phone"),
    (r"^iphone$", "link my phone"),
    (r"^companion$", "open phone companion"),
    (r"^phone companion$", "open phone companion"),
    (r"^companion zip$", "companion zip"),
    (r"^setup zip$", "companion zip"),
    (r"^ping( my)? phone$", "ping my phone"),
    (r"^text( my)? phone$", "ping my phone"),
    (r"^notify( my)? phone$", "ping my phone"),
    (r"^pink( my)? phone$", "ping my phone"),
    (r"^snapchat( setup| status| link)?$", "snapchat setup"),
    (r"^snap( call)? (setup|link)$", "snapchat setup"),
    (r"^link snap(chat)?$", "snapchat setup"),
    (r"^link (my )?snap(chat)?$", "snapchat setup"),
    (r"^live comms( setup| status)?$", "live comms setup"),
    (r"^message translate( setup)?$", "live comms setup"),
    (r"^phone link( setup| install| open)?$", "setup phone link"),
    (r"^setup phone link$", "setup phone link"),
    (r"^link (my )?iphone to (windows|pc)$", "setup phone link"),
    (r"^test live comms$", "test live comms"),
    (r"^test (imessage|instagram|snap) translate$", "test live comms"),
    (r"^test snap(chat)?( call)?$", "test snapchat call"),
    (r"^answer snap(chat)?$", "answer snapchat"),
    (r"^approve$", "approve"),
    (r"^reject$", "reject"),
    (r"^thumbs up$", "approve"),
    (r"^thumbs down$", "reject"),
    # Travis personality modes
    (r"^travis$", "travis status"),
    (r"^park$", "park mode"),
    (r"^park mode$", "park mode"),
    (r"^tactical$", "tactical protocol"),
    (r"^tacticals$", "tactical protocol"),
    (r"^tactical (protocol|mode)$", "tactical protocol"),
    (r"^peer$", "peer review mode"),
    (r"^peer review$", "peer review mode"),
    (r"^critique$", "peer review mode"),
    (r"^travis off$", "travis mode off"),
    (r"^standard protocol$", "travis mode off"),
    # Workflows / registry / monitor (additive)
    (r"^morning( workflow| routine)?$", "run morning workflow"),
    (r"^night( workflow| routine)?$", "run night workflow"),
    (r"^focus workflow$", "run focus workflow"),
    (r"^focus routine$", "run focus workflow"),
    (r"^run secure workflow$", "run secure workflow"),
    (r"^workflows?$", "list workflows"),
    (r"^registry$", "feature status"),
    (r"^features?$", "feature status"),
    (r"^monitor$", "show command monitor"),
    (r"^disk$", "disk space"),
    (r"^vitals$", "status"),
    (r"^lamp status$", "lamp status"),
    (r"^toggle lamp$", "toggle the lamp"),
    (r"^coding mode$", "coding mode"),
    (r"^reading mode$", "reading mode"),
    (r"^grab voice$", "grab voice"),
    (r"^clone voice$", "grab voice"),
    (r"^voice clone status$", "voice clone status"),
    (r"^list (voice )?clones$", "list voice clones"),
    # AI Systems v2
    (r"^systems$", "systems status"),
    (r"^systems v2$", "systems status"),
    (r"^systems status$", "systems status"),
    (r"^ai systems$", "systems status"),
    (r"^ai systems status$", "systems status"),
    (r"^upgrade systems$", "systems upgrade"),
    (r"^systems upgrade$", "systems upgrade"),
    (r"^mistweb$", "mistweb status"),
    (r"^mistweb status$", "systems status"),
    (r"^tick list$", "tick list"),
    (r"^tick start$", "tick start"),
    (r"^tick stop$", "tick stop"),
    (r"^swe bench$", "swe-bench status"),
    (r"^swe-bench$", "swe-bench status"),
    (r"^swe-bench status$", "swe-bench status"),
    (r"^cloud agent status$", "cloud agent status"),
    (r"^langgraph status$", "systems status"),
    (r"^pydad status$", "systems status"),
    (r"^agno status$", "systems status"),
    (r"^llama index status$", "systems status"),
    (r"^highway to hell$", "play highway to hell"),
    (r"^play highway to hell$", "play highway to hell"),
    (r"^daddy'?s home$", "daddy's home"),
    (r"^daddys home$", "daddy's home"),
    (r"^i'?m home$", "daddy's home"),
    (r"^tony'?s home$", "daddy's home"),
    (r"^stark arrival$", "daddy's home"),
    (r"^workshop music$", "play iron man workshop"),
    # Manus AI (https://manus.im)
    (r"^manus$", "manus status"),
    (r"^manus status$", "manus status"),
    (r"^link manus$", "link manus"),
    (r"^connect manus$", "link manus"),
    (r"^setup manus$", "link manus"),
    (r"^check manus$", "check manus"),
    (r"^manus result$", "manus result"),
    (r"^manus progress$", "manus progress"),
    (r"^manus review$", "manus review"),
    (r"^review this with manus$", "manus review"),
    (r"^manus improve( this)?$", "manus review"),
    (r"^ask manus to improve( this)?$", "manus review"),
    (r"^improve this with manus$", "manus review"),
    # Computer-use / browser agent
    (r"^computer use$", "computer use status"),
    (r"^computer use status$", "computer use status"),
    (r"^browser agent$", "computer use status"),
    (r"^browser agent status$", "computer use status"),
    (r"^operator status$", "computer use status"),
    (r"^stop computer use$", "stop computer use"),
    (r"^cancel computer use$", "stop computer use"),
    (r"^stop browser agent$", "stop computer use"),
    (r"^stop operator$", "stop computer use"),
    (r"^setup computer use$", "setup computer use"),
    (r"^link computer use$", "setup computer use"),
    (r"^computer use provider local$", "computer use provider local"),
    (r"^computer use provider ollama$", "computer use provider ollama"),
    (r"^computer use provider free$", "computer use provider free"),
    # Cloud integrations (Stripe / Notion / Buffer / Gmail)
    (r"^integrations?$", "integrations status"),
    (r"^integrations? status$", "integrations status"),
    (r"^cloud status$", "integrations status"),
    (r"^stripe$", "stripe status"),
    (r"^stripe status$", "stripe status"),
    (r"^stripe payments$", "stripe payments"),
    (r"^link stripe$", "link stripe"),
    (r"^notion$", "notion status"),
    (r"^notion status$", "notion status"),
    (r"^link notion$", "link notion"),
    (r"^buffer$", "buffer status"),
    (r"^buffer status$", "buffer status"),
    (r"^buffer channels$", "buffer channels"),
    (r"^link buffer$", "link buffer"),
    (r"^gmail$", "gmail status"),
    (r"^gmail status$", "gmail status"),
    (r"^gmail inbox$", "gmail inbox"),
    (r"^check (my )?email$", "gmail inbox"),
    (r"^clear email$", "clear email"),
    (r"^clear (my )?emails$", "clear email"),
    (r"^clear (my )?inbox$", "clear email"),
    (r"^empty (my )?inbox$", "clear email"),
    (r"^inbox zero$", "clear email"),
    (r"^trash all (my )?email$", "trash all email"),
    (r"^link gmail$", "link gmail"),
    (r"^setup gmail oauth$", "setup gmail oauth"),
    (r"^gmail oauth$", "setup gmail oauth"),
    (r"^my progress$", "summarize my progress"),
    (r"^progress$", "summarize my progress"),
    (r"^progress report$", "summarize my progress"),
    (r"^cash app$", "cash app spending"),
    (r"^cash app spend(ing)?$", "cash app spending"),
    (r"^sync cash app$", "sync cash app"),
    (r"^link icloud$", "link icloud mail"),
    (r"^icloud$", "icloud status"),
    (r"^icloud status$", "icloud status"),
    (r"^personality forge$", "personality forge status"),
    (r"^forge status$", "personality forge status"),
    (r"^generate personality dataset$", "generate personality dataset"),
    (r"^forge personality data$", "generate personality dataset"),
    (r"^train personality$", "train personality"),
    (r"^start dpo$", "start dpo training"),
    (r"^harvest rlhf$", "harvest rlhf for training"),
    (r"^use my mic$", "use my mic"),
    (r"^mic status$", "microphone status"),
    (r"^tactical briefing$", "tactical briefing"),
    (r"^casual briefing$", "casual briefing"),
    (r"^blind spot briefing$", "blind spot briefing"),
    (r"^house party protocol$", "house party protocol"),
    (r"^sentry mode$", "sentry mode"),
    (r"^veronica protocol$", "veronica protocol"),
    (r"^surprise me$", "surprise me"),
    (r"^devil'?s advocate$", "devil's advocate"),
    (r"^pitch a project$", "pitch a project"),
    (r"^what'?s shaking$", "what's shaking the grid"),
    (r"^workshop stock$", "workshop stock"),
    (r"^package status$", "package status"),
    (r"^cron status$", "cron status"),
    (r"^cognitive status$", "cognitive status"),
    (r"^executive role$", "set cognitive role to executive"),
    (r"^research role$", "set cognitive role to research"),
    (r"^open hologram$", "open hologram"),
    (r"^hologram$", "open hologram"),
    (r"^fabricator$", "open fabricator"),
    (r"^stark lab$", "open fabricator"),
    (r"^suit lab$", "open fabricator"),
    (r"^edith$", "open fabricator"),
    (r"^phaser web$", "open fabricator"),
    (r"^build (the )?suit$", "build the suit"),
    (r"^fabricate (the )?suit$", "build the suit"),
    (r"^aerospatial$", "open aerospatial"),
    (r"^open aerospatial$", "open aerospatial"),
    (r"^ar map$", "open aerospatial"),
    (r"^spatial mesh$", "open aerospatial"),
    (r"^room scan$", "scan room"),
    (r"^scan (the )?room$", "scan room"),
    (r"^laser scan (the )?room$", "scan room"),
    (r"^aerospatial setup$", "aerospatial setup"),
    (r"^ar setup$", "aerospatial setup"),
    (r"^aerospatial desktop$", "aerospatial desktop"),
    (r"^aerospatial mirror$", "aerospatial mirror"),
    (r"^aerospatial phone$", "aerospatial phone"),
    (r"^ar desktop$", "aerospatial desktop"),
    (r"^ar mirror$", "aerospatial mirror"),
    (r"^ar phone$", "aerospatial phone"),
    (r"^close aerospatial$", "close aerospatial"),
    (r"^close ar$", "close aerospatial"),
    (r"^cinematic ar$", "cinematic ar"),
    (r"^smooth ar$", "cinematic ar"),
    (r"^fix jitter$", "cinematic ar"),
    (r"^web shooter$", "web shooter"),
    (r"^ar biometric$", "ar biometric"),
    (r"^ar gauges$", "ar gauges"),
    (r"^pinecone status$", "pinecone status"),
    (r"^live voice status$", "live voice status"),
    (r"^computer use anthropic$", "computer use anthropic"),
    (r"^prefer elevenlabs$", "prefer elevenlabs"),
    (r"^suggestions off$", "suggestions off"),
    (r"^stop suggesting$", "suggestions off"),
    (r"^suggestions on$", "suggestions on"),
    (r"^wake word only$", "wake word only"),
    (r"^always listen$", "always listen"),
    (r"^ha status$", "home assistant status"),
    (r"^task(s)? status$", "task status"),
    # Productivity suite (additive)
    (r"^auto commit$", "auto commit"),
    (r"^commit (and )?push$", "auto commit and push"),
    (r"^git status$", "git status"),
    (r"^tech news$", "tech news"),
    (r"^gaming news$", "gaming news"),
    (r"^price check$", "check prices"),
    (r"^voice code$", "start voice to code"),
    (r"^dictate code$", "start voice to code"),
    (r"^mood$", "mood status"),
    (r"^proactive on$", "proactive on"),
    (r"^proactive off$", "proactive off"),
    # Security / gestures / autobug
    (r"^enrol+l?( face)?$", "enroll my face"),
    (r"^enrol+ my face$", "enroll my face"),
    (r"^security$", "security status"),
    (r"^intruder alerts? off$", "intruder alerts off"),
    (r"^intruder alerts? on$", "intruder alerts on"),
    (r"^no intruder alerts?$", "intruder alerts off"),
    (r"^disarm security$", "disarm security"),
    (r"^security off$", "disarm security"),
    (r"^security on$", "arm security"),
    (r"^task complete$", "mark task complete"),
    (r"^autobug$", "fix this error"),
    (r"^self audit$", "self audit"),
    (r"^copy$", "hit copy"),
    (r"^paste$", "hit paste"),
    (r"^save$", "hit save"),
    (r"^undo$", "hit undo"),
    (r"^night vision off$", "night vision off"),
    (r"^night vision on$", "night vision on"),
    (r"^nvg off$", "night vision off"),
    (r"^night vision$", "night vision on"),
    (r"^auto lock off$", "auto lock off"),
    (r"^auto lock on$", "auto lock on"),
    (r"^router status$", "router status"),
    (r"^spatial on$", "spatial gestures on"),
    (r"^spatial off$", "spatial gestures off"),
    (r"^spatial$", "spatial status"),
    # Smart desk (2026-07-23)
    (r"^suggestions? off$", "suggestions off"),
    (r"^stop suggesting$", "suggestions off"),
    (r"^suggestions? on$", "suggestions on"),
    (r"^quiet( mode)?$", "quiet mode"),
    (r"^loud( mode)?$", "loud mode"),
    (r"^mute alerts$", "quiet mode"),
    (r"^unmute alerts$", "loud mode"),
    (r"^do not disturb$", "quiet mode"),
    (r"^desk ready$", "desk ready"),
    (r"^prep desk$", "desk ready"),
    (r"^smooth( mode)?$", "smooth mode"),
    (r"^performance mode$", "smooth mode"),
    (r"^eco( hud| mode)?$", "smooth mode"),
    (r"^smooth mode off$", "smooth mode off"),
    (r"^performance mode off$", "smooth mode off"),
    (r"^full fidelity$", "smooth mode off"),
    (r"^exit smooth$", "smooth mode off"),
    (r"^full status$", "full status"),
    (r"^systems overview$", "full status"),
    (r"^upgrade status$", "upgrade status"),
    (r"^upgrade check$", "upgrade check"),
    (r"^self health$", "upgrade check"),
    (r"^health check$", "upgrade check"),
    (r"^desk health$", "upgrade check"),
    (r"^system health$", "upgrade check"),
    (r"^recent errors$", "recent errors"),
    (r"^show (recent )?errors$", "recent errors"),
    (r"^log errors$", "recent errors"),
    (r"^summarize (my )?day$", "summarize my day"),
    (r"^day summary$", "summarize my day"),
    (r"^summarize clipboard$", "summarize clipboard"),
    (r"^clipboard summary$", "summarize clipboard"),
    # Manus / Hub ask forms
    (r"^ask manus$", "manus status"),
    # Home ops / edge / cyber / space
    (r"^net watch$", "net watch status"),
    (r"^lan scan$", "scan the network"),
    (r"^trust network$", "trust the network"),
    (r"^run backup$", "run backup"),
    (r"^backup now$", "run backup"),
    (r"^backup status$", "backup status"),
    (r"^arm deadman$", "arm deadman"),
    (r"^disarm deadman$", "disarm deadman"),
    (r"^deadman$", "deadman status"),
    (r"^space weather$", "space weather"),
    (r"^solar storm$", "space weather"),
    (r"^iss$", "iss status"),
    (r"^scan processes$", "scan processes"),
    (r"^harden$", "chris titus"),
    (r"^edge setup$", "edge setup"),
    (r"^home ops$", "home ops status"),
    (r"^jetson$", "edge setup"),
    # Triple monitor layout
    (r"^triple monitors$", "engage triple monitors"),
    (r"^triple layout$", "engage triple monitors"),
    (r"^command deck$", "open command deck"),
    (r"^tools panel$", "open tools panel"),
    (r"^screen 2$", "open tools panel"),
    (r"^screen 3$", "open command deck"),
    (r"^list monitors$", "list monitors"),
]


def normalize_command(text: str) -> str:
    """Expand short aliases; leave full sentences untouched."""
    raw = (text or "").strip()
    if not raw:
        return raw
    low = raw.lower().strip(" .!?")
    for pattern, canon in _ALIASES:
        if re.fullmatch(pattern, low, re.I):
            return canon
    # Soft cleanup of wake leftovers already handled in brain; strip filler here
    low2 = re.sub(r"^(please|just|can you|could you|would you)\s+", "", low)
    if low2 != low:
        for pattern, canon in _ALIASES:
            if re.fullmatch(pattern, low2, re.I):
                return canon
    return raw


# Exact control-strip utterances + common spoken forms (post-normalize).
# Used for one-shot local routing (no Hub/memory/suggestion lag).
_FAST_LOCAL_CMDS: frozenset[str] = frozenset(
    {
        "open camera",
        "look at my screen",
        "play music",
        "check email",
        "open map view",
        "zoom in",
        "zoom out",
        "pull up the news",
        "show stats",
        "open pdtester",
        "away mode",
        "build a site",
        "start vibe coding",
        "find biz",
        "search the web for latest AI news",
        "enroll my face",
        "security status",
        "night vision off",
        "night vision on",
        "auto lock off",
        "auto lock on",
        "self audit",
        "fix this error",
        "router status",
        "secure desk",
        "lock",
        "unlock my pc",
        "sleep",
        "panic",
        "status",
        "hub standby",
        "quiet mode",
        "loud mode",
        "desk ready",
        "smooth mode",
        "smooth mode off",
        "full status",
        "upgrade status",
        "upgrade check",
        "recent errors",
        "summarize my day",
        "summarize clipboard",
        "intruder alerts off",
        "intruder alerts on",
        "computer use status",
        "stop computer use",
        "setup computer use",
        "computer use provider local",
        "snapchat setup",
        "test snapchat call",
        "answer snapchat",
        "live comms setup",
        "test live comms",
        "setup phone link",
        "phone link setup",
        "doorbell setup",
        "test doorbell",
        "link my phone",
        "ping my phone",
        "phone status",
        "good morning",
        "list reminders",
        "my reminders",
        "cancel all reminders",
        "optimize jarvis",
        "upgrade everything",
        "set up my morning workspace",
        "morning setup",
        "help",
        "open aerospatial",
        "scan room",
        "aerospatial setup",
        "close aerospatial",
        "aerospatial status",
        "cinematic ar",
        "web shooter",
        "ar biometric",
        "engage triple monitors",
        "open tools panel",
        "open command deck",
        "grab voice",
        "list voice clones",
        "voice clone status",
        "speak as clone hello",
        "clear voice clone",
        "list monitors",
        "ar gauges",
        "net watch status",
        "scan the network",
        "trust the network",
        "run backup",
        "backup status",
        "arm deadman",
        "disarm deadman",
        "deadman status",
        "space weather",
        "iss status",
        "scan processes",
        "chris titus",
        "edge setup",
        "home ops status",
    }
)

# Prefix / substring match so spoken variants skip "On it." double-TTS.
_FAST_LOCAL_PREFIXES: tuple[str, ...] = (
    "remind me",
    "reminder ",
    "set a reminder",
    "set reminder",
    "nudge me",
    "list reminder",
    "cancel reminder",
    "snapchat",
    "test snap",
    "answer snap",
    "live comms",
    "message translate",
    "phone link",
    "setup phone",
    "doorbell",
    "good morning",
    "morning brief",
    "daily brief",
    "optimize jarvis",
    "morning workspace",
    "morning setup",
    "aerospatial",
    "scan room",
    "ar map",
    "spatial mesh",
    "net watch",
    "trust network",
    "run backup",
    "backup status",
    "arm deadman",
    "disarm deadman",
    "deadman",
    "space weather",
    "solar storm",
    "iss status",
    "scan process",
    "chris titus",
    "edge setup",
    "home ops",
    "translate to",
    "triple monitor",
    "engage triple",
    "tools panel",
    "command deck",
    "list monitors",
)


def is_fast_local_command(text: str) -> bool:
    """True for HUD strip cmds that must stay local + single-speak."""
    low = normalize_command(text or "").lower().strip(" .!?")
    if not low:
        return False
    if low in _FAST_LOCAL_CMDS:
        return True
    return any(low.startswith(p) or p in low for p in _FAST_LOCAL_PREFIXES)
